### ISSUE TITLE
Custom header in HttpRequest get

### ISSUE THREAD

**Issue by frazzaglia** [kevinsawicki/http-request#132]
Hi all,

I don't be able to add a custom headers to HttpRequest.
I tried with:

```
HttpRequest.get(url).basic(username,password);
req.header("myCustomHeader", "true");
...
```
but no custom header is added to http request.
How can I solve it? What's the problem?
Thanks.

**Comment by rferreira** [comment]
As described in the documentation, you need to set the headers while creating the HttpRequest: 

```
String contentType = HttpRequest.get("http://google.com")
                                .accept("application/json") //Sets request header
                                .contentType(); //Gets response header

```

afterwards is too late.

**Comment by frazzaglia** [comment]
@rferreira Thanks for the reply.
I have another little problem, with:

`HttpRequest req = HttpRequest.get(url).basic(user.getUsername(), user.getPassword()).header("myCustomHeader", "true");`

it doesn't work, but with:

`HttpRequest req = HttpRequest.get(url).header("Authorization", "Basic dasadjosjdajsodiajiosd").header("myCustomHeader", "true");`

it works fine.
Why?
Thanks a lot.

**Comment by rferreira** [comment]
Not work how? What error are you seeing?

**Comment by frazzaglia** [comment]
I'm sorry, it was my mistake. 
Your solution works fine.
Thanks a lot.

I'm going to close this issue.
