### ISSUE TITLE
Problem when encoding the '+' charcter

### ISSUE THREAD

**Issue by julienlancelot** [kevinsawicki/http-request#38]
When using HttpRequest.get() with encode parameter to 'true', the '+' (for instance in /my-server/my-action?a-date=2013-01-01T00:00:00+0100) is not encoded to "%2B", but with a blank character.
The same when using HttpRequest.post().

Thanks!

**Comment by logan676** [comment]
Now I have a problem when encoding `/` and `&`, I am using `com.github.kevinsawicki:http-request:5.6`
