### ISSUE TITLE
Headers in HttpRequest

### ISSUE THREAD

**Issue by aliilyas** [kevinsawicki/http-request#51]
I want to add headers to HttpRequest, i've tried to use header and parameter method but it did not worked for me, can you show some examples of usage?

**Comment by frazzaglia** [comment]
Hi all,

I don't be able to add a custom headers to HttpRequest. 
I tried with:

```
HttpRequest.get(url).basic(username,password);
req.header("myCustomHeader", "true");
...
```
but no custom header is added to http request.
How can I solve it? What's the problem?
Thanks.
