### ISSUE TITLE
Download Progress

### ISSUE THREAD

**Issue by jerson** [kevinsawicki/http-request#84]
Hello, I have a silly question, probably because I'm either doing something wrong. 

in your example

        file = File.createTempFile("download", ".tmp");
        request.receive(file);
        publishProgress(file.length());
      
but 

        publishProgress(file.length());

only used once. How the process of the download is sent?

**Comment by tqcenglish** [comment]
This is my solution method.

          new Thread() {
                        @Override
                        public void run() {
                            while (request.getConnection().getContentLength() != file.length()) {
                                publishProgress(file.length());
                                SystemClock.sleep(800);
                            }
                        }
                    }.start();
           request.receive(file);

**Comment by jerson** [comment]
Thanks @tqcenglish
