### ISSUE TITLE
How to make a GET request to server and get response code and response body separately

### ISSUE THREAD

**Issue by marceloquinta** [kevinsawicki/http-request#86]
Hello, I need to make a GET request to server and get response code and response body separately.  

How can I do that?

https://stackoverflow.com/questions/25414324/get-response-code-and-response-body-ina-a-single-request-using-http-request

**Comment by rsbulanon** [comment]
calling HttpRequest.body() and HttpRequest.code() needs to be placed inside of an ansyctask, so how can i call them both if that's the case?

**Comment by kevinsawicki** [comment]
> calling HttpRequest.body() and HttpRequest.code() needs to be placed inside of an ansyctask, so how can i call them both if that's the case?

I'm not sure I understand your question, can you include a code snippet of what you are trying to do or what isn't working for you?

**Comment by rsbulanon** [comment]
when i call HttpRequest.body() or HttpRequest.code() directly, it causes NetworkOnMainThread

**Comment by marceloquinta** [comment]
Yes, you need to put it in a separate thread (AsyncTask/Service), different
than main/UI thread. It's a Android rule.

2015-08-21 0:33 GMT-03:00 rsbulanon notifications@github.com:

> when i call HttpRequest.body() or HttpRequest.code() directly, it causes
> NetworkOnMainThread
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kevinsawicki/http-request/issues/86#issuecomment-133267942
> .

## 

_Marcelo Quinta_
_-----------------------------@mrquinta_

**Comment by rsbulanon** [comment]
Yeah i'm aware that i need to put it inside of an AsyncTask, but my question is, how can i get the status code and body at once. It seems that i need to provide two different asynctask because .code() returns integer and .body() returns String.
